### ISSUE TITLE
您好，请问怎么去掉中英文摘要前面的论文标题呢

### ISSUE THREAD

**Issue by lqCyliu** [YunYouJun/cucthesis#1]

**Comment by YunYouJun** [comment]
请截图示意。

**Comment by lqCyliu** [comment]
![1675820517313](https://user-images.githubusercontent.com/54386549/217407311-fa835c92-7608-4024-b51a-e596c1e90cab.jpg)
您好，就是这个中英文摘要前面的论文标题

**Comment by YunYouJun** [comment]
尝试删除：

https://github.com/YunYouJun/cucthesis/blob/33bb371cd6f34d868170b64f55b5d4ce7213e252/thuthesis.dtx#L5046-L5056

thuthesis.dtx 中搜索 `% CUC` 为自定义部分。

**Comment by lqCyliu** [comment]
非常感谢，在您的帮助下已经解决了
