### ISSUE TITLE
main.tex中封面与声明的顺序与学校编写规则中的顺序不一致

### ISSUE THREAD

**Issue by TheMasterOfMagic** [YunYouJun/cucthesis#2]
在本仓库的[cuc/中国传媒大学研究生学位论文编写规则（自然科学版）20211230.pdf](https://github.com/YunYouJun/cucthesis/blob/main/cuc/%E4%B8%AD%E5%9B%BD%E4%BC%A0%E5%AA%92%E5%A4%A7%E5%AD%A6%E7%A0%94%E7%A9%B6%E7%94%9F%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E7%BC%96%E5%86%99%E8%A7%84%E5%88%99%EF%BC%88%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6%E7%89%88%EF%BC%8920211230.pdf)文件中，正文第2页写到：

<img width="635" alt="image" src="https://user-images.githubusercontent.com/25054321/220039481-2cabb882-5ff1-4dba-9d4a-4ba719014ff4.png">

可以看到，顺序是`封面 - 声明 - 摘要`。

而在main.tex中：
https://github.com/YunYouJun/cucthesis/blob/0aa192402aad5034d17d0b33d62ae6a6c114550e/main.tex#L29-L42

可以看到，顺序是`声明 - 封面 - 摘要`。

我想知道这个顺序安排是基于哪方面的考量呢，还是说只是疏忽了？

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/220090188-f949a4f1-0ab4-4870-bed6-32c96015b12c.png)

如截图所示，顺序为 `封面` `声明` `摘要`。

**Comment by TheMasterOfMagic** [comment]
😂还真是。我一直都是把33行的注释取消了来用的，没注意到37行有个现成的命令。感谢解答。
