### ISSUE TITLE
目录页中包含摘要等其它内容

### ISSUE THREAD

**Issue by TheMasterOfMagic** [YunYouJun/cucthesis#3]
关于目录的内容，CUC的编写规则中是这么写的：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/25054321/224666318-d7c686c3-a2c8-4084-abb6-be9ff4cd9a7f.png">
可以看到是不包含摘要等正文部分之前的内容的。包括其中提到的附件4也是如此：
<img width="740" alt="image" src="https://user-images.githubusercontent.com/25054321/224666435-c776df27-eb07-4cd9-9c33-f272bb85733e.png">
可目前的模板所编译出来的结果中，是包含了正文部分之前的摘要以及一些其它内容的。例如本仓库示例PDF的目录页就是这样：
<img width="677" alt="image" src="https://user-images.githubusercontent.com/25054321/224666783-1ae1eb0f-f6b3-4366-9a31-929dce834c15.png">
我试着自己去修改了一下`thuthesis.dtx`但这个效果没有搞出来😂这个应当如何实现呢？

**Comment by TheMasterOfMagic** [comment]
我试出来了，在`main.tex`中，在`\frontmatter`之前加入一行`\addtocontents{toc}{\protect\setcounter{tocdepth}{-1}}`，在`\mainmatter`之前加入一行`\addtocontents{toc}{\protect\setcounter{tocdepth}{2}}`可以实现这个修改。

**Comment by YunYouJun** [comment]
感觉不改也问题不大（
